version: '3'
services:
  nextjs:
    build:
      context: .
    ports:
      - '3000:3000'
    restart: always
    networks:
      - nextjs-blog

  pocketdb:
    build:
      context: ./pocketbase
    ports:
      - '8080:8080'
    restart: always
    volumes:
      - ./pocketbase/pb_data:/pb_data
    networks:
      - nextjs-blog

networks:
  nextjs-blog:
